# Generated by Django 5.1.6 on 2026-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='heart_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_notes',
            field=models.TextField(blank=True),
        ),
    ]
