# Generated by Django 5.2.15 on 2026-06-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_seed_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, e.g. 994501112233. Used to build the wa.me link.', max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('instagram_handle', models.CharField(blank=True, max_length=80)),
                ('tiktok_url', models.URLField(blank=True)),
                ('tiktok_handle', models.CharField(blank=True, max_length=80)),
                ('store_address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
