# Generated by Django 5.0.14 on 2026-06-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productvariant_is_default'),
        ('shop', '0029_seed_site_settings'),
    ]

    operations = [
    ]
