# Generated by Django 5.2.15 on 2026-06-09 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_contactmessage_is_read_order_email_order_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promoredemption',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usercartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'product'), name='uniq_default_cart_item_per_user_product'),
        ),
    ]
