# Generated by Django 5.2.15 on 2026-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_fix_gram_price_and_backfill_default_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_text',
            field=models.CharField(blank=True, help_text='Promo strip headline. Leave blank to use the default translated line.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gram_image_url',
            field=models.URLField(blank=True, help_text='Shared packaging image used for gram variants that have no image of their own.'),
        ),
    ]
