# Generated by Django 5.2.15 on 2026-06-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_sitesettings_banner_text_sitesettings_gram_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('about', 'About'), ('faq', 'FAQ'), ('privacy', 'Privacy'), ('terms', 'Terms')], max_length=40)),
                ('language', models.CharField(choices=[('az', 'Azərbaycan'), ('en', 'English'), ('ru', 'Русский')], default='az', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug', 'language'),
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
