# Generated by Django 5.2.15 on 2026-06-09 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_sitesettings_gram_size_images'),
        ('shop', '0035_staticpage'),
    ]

    operations = [
    ]
