# Generated by Django 5.2.15 on 2026-06-14 08:42

from django.db import migrations, models


def forwards_copy_new_flag(apps, schema_editor):
    """Products previously flagged is_new_arrival=True become 'always' so the
    'Yeni' badge keeps showing for them; everything else defaults to 'auto'
    (date-based), which is the new behaviour."""
    Product = apps.get_model("shop", "Product")
    Product.objects.filter(is_new_arrival=True).update(new_badge_mode="always")


def backwards_copy_new_flag(apps, schema_editor):
    Product = apps.get_model("shop", "Product")
    Product.objects.filter(new_badge_mode="always").update(is_new_arrival=True)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_merge_20260610_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_badge_mode',
            field=models.CharField(choices=[('auto', 'Avtomatik (yaradılma tarixinə görə)'), ('always', 'Həmişə yeni göstər'), ('never', 'Heç vaxt göstərmə')], default='auto', help_text="'Yeni' nişanı: Avtomatik (yaradılma tarixindən N gün), Həmişə, və ya Heç vaxt.", max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='new_badge_days',
            field=models.PositiveIntegerField(default=7, help_text="Avtomatik 'Yeni' nişanı: məhsul əlavə edildikdən sonra neçə gün yeni sayılsın. 0 = avtomatik söndürülür."),
        ),
        migrations.RunPython(forwards_copy_new_flag, backwards_copy_new_flag),
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
    ]
